language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
# command to install dependencies
install:
  - "pip install pipenv"
  - "pip install coveralls"
  - "pip install tox-travis"
  - 'pipenv sync'
# command to run tests
script:
  - "tox"
# send coverage report
after_success:
  - "make coveralls"
