language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script:
  - pytest tests/ --cov=bsdapi
# send coverage report
after_success:
  - coveralls